---
title: ""
output:
  html_document
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}
###### STEP 1: SOURCE from the script that has: styling, packages, dbconnection, colors #####
library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("chart_functions.R")
pillars_conn <- connect_to_db("rjs_pillars")

```

```{r, include=FALSE}
###### STEP 2: DOWNLOAD and PREP data frame #####

# Example:
## Load in RJS Pillars data: Bubble Pop test ##
# df <- dbGetQuery(pillars_conn, "SELECT * FROM data.report_gang_stoprates_race_person")%>% filter(race!="total" & !is.na(stop_count))

# Pull df from postgres (filter, format, and reorder as needed)

df <-dbGetQuery(con, "SQL QUERY HERE") 


```

```{r, echo=FALSE}
###### STEP 3: INSERT text needed in the visual #####

# TITLE 
title_text <- paste0("An overwhelming majority of people support an IRC.")

# SUBTITLE
subtitle_text <- paste0("Percent of people by degree of support for an IRC")

# CAPTION

caption_text <- paste0(racenote,"<br><br>", sourcenote, "<br>")

# TOOLTIP
# note you may need to add a new field to your dataframe to format tooltip text more

tooltip_text <- "<b>{point.rate:.0f}%</b> of people {point.value_tooltip} an IRC"

```

```{r, echo=FALSE}
###### STEP 4: VISUALIZE #####

# Chart options include:
# fx_bubblepopchart
# fx_itemchart
# fx_stackedbarchart

# See chart_functions.R for more documentation on each chart's arguments

# Example:

chart <- fx_bubblepopchart(
  df=df,
  x='race', # format for your data frame
  y='stop_per1k_rate', # format for your data frame
  z='stop_count', # format for your data frame
  top_finding=title_text,
  subtitle= subtitle_text,
  tooltip_text=tooltip_text,
  caption = caption_text,
  yaxis_label = "''", # format for your y axis labels
  export_data_label=list(pointFormat='{point.stop_rate_per1k:.1f} per 1K') # format for your data
)

```

```{r, include = FALSE}
# STEP 5: CLOSE postgres connection
dbDisconnect(pillars_conn) 
```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>