---
title: ""
output:
  html_document
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
```{r, include=FALSE}

#### Testing bubblepop ####
library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("W:\\Project\\RJS\\Pillars\\GitHub\\HK\\sdpillars\\report_embeds\\chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")
## load in race metadata
metadata_race_labels <-  dbGetQuery(pillars_conn, "SELECT * FROM metadata_race_labels") %>% select(race_base, race_label_short, race_label_long)

## Load in RJS Pillars data
df <- dbGetQuery(pillars_conn, "SELECT * FROM report_stoprates_race_gang_person") %>% filter(race!="total" & race != "nhpi" & race!= "aian" & !is.na(stop_count) & stop_count != "0") %>% left_join(metadata_race_labels, by = c("race" = "race_base")) %>% mutate(race_label_long = 
                                                                                                                                                                                                                                            ifelse(race %in% "nh_aian", "American Indian or Alaska Native",
                                                                                                                                                                                                                                           ifelse(race %in% "nh_nhpi", "Native Hawaiian or Pacific Islander", race_label_long)
                                                                                                                                                                                                                                            )) %>% 
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           mutate(race_label_short = 
                                                                                                                                                                                                                                            ifelse(race %in% "nh_aian", "AIAN",
                                                                                                                                                                                                                                           ifelse(race %in% "nh_nhpi", "NHPI", race_label_short)
                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                           )
                                                          

chart <- fx_bubblepopchart(
  df=df, 
  x='race_label_short', 
  y='stop_prc_rate', 
  z='stop_count',
  top_finding=paste0("SDPD profiles Black and Latinx people for gang activity at higher rates than other community members."), # this is the top finding from the chart that gets used like a title
  subtitle= paste0("Number of officer initiated, gang enforcement assignment stops per total gang enforced stops by Race and Ethnicity"), # this is the more standard chart title that gets used as a subtitle
  tooltip_text="Out of the <b>{point.stop_total_count:.1f}</b> total gang enforced stops, SDPD stopped <b>{point.stop_count:.1f}</b> people perceived as <b>{point.race_label_long:.1f}</b>, a rate of  <b>{point.stop_prc_rate:.1f}</b>%.", # customize your tooltip as a statement, calling out rate and count
  caption = paste0(racenote,"<br><br>", sourcenote, "<br>","Analysis for all officer-initiated stops.","<br>"), # if necessary add a method note between the racenote and sourcenote with a line break, use racenote if graph includes data by race, and always use sourcenote. Each of these are standard objects across all charts
  yaxis_label = "''", #format for your y axis labels
  export_data_label=list(pointFormat='{point.stop_rate_per1k:.1f} per 1K')
)

dbDisconnect(pillars_conn)

```


```{r, echo=FALSE}
chart
```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>