---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

library(RPostgreSQL)
library(tidyverse)
source("W:\\RDA Team\\R\\credentials_source.R")
source("chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")

df <- dbGetQuery(pillars_conn, "SELECT * FROM report_timespent_div_ficard_race_person") 

# Pivot table to longer for graphing

df1<-df%>%
  select(div_name, div, race, stop_result_simple, duration_rate, pop_rate)%>%
  filter(stop_result_simple=="Field interview card completed")%>%
    pivot_longer(5:6, names_to = "measure", values_to = "value")%>%
  filter(!is.na(value)) # no pop estimates for nh_sswana & nh_multi_race

# join wide version table back to it because we need those separate columns for the tooltip later

df1<-df1%>%
  left_join(df)%>%
     mutate(div_name=str_to_title(div_name))


```


```{r, include=FALSE}

# add methodnote
methodnote <- "Analysis for all officer-initiated stops resulting in a field interview card only in each SDPD division. Officers spent a total of 118,970.3 hours on officer-initiated stops that resulted in a field interview card only in 2022."

# create caption
caption_text <- paste("<br><br>", sourcenote, methodnote)

# add title and subtitle
top_finding<-"Across all SDPD divisions, SDPD disproportionately spends time on field interview cards for Black people relative to their population"
subtitle<-"Percent of hours officers spent stopping people they perceived as Black that resulted in a field interview card by SDPD division"

# tooltip

tooltip_text<- paste0("Out of all hours spent on <b>officer-initiated stops resulting in a field<br>interview card</b> in the <b>{point.div_name} Division (Division {point.div})</b>, SDPD spent<br><b>{point.duration_rate:.1f}%</b> of those hours conducting field interviews on people perceived<br>as <b>Black</b>. By comparison, <b>Black people</b> make up just <b>{point.pop_rate:.1f}%</b> of the total<br>population in the <b>{point.div_name} Division</b>")

# Final Graph----------------

# set ordering

df1<-df1%>%
        mutate(measure=ifelse(measure %in% 'pop_rate','Percent of total population','Percent time spent'))

df1$measure <- factor(df1$measure, levels = c("Percent time spent", "Percent of total population"))


chart<-df1 %>% 
  arrange(div, -value)%>%
  filter(race=='nh_black')%>%
  hchart('bar', hcaes(x = div_name, y = value, group = measure),
         tooltip =  list(headerFormat='',pointFormat=tooltip_text)) %>%
  hc_colors(c("#211447", peridot))%>%
   hc_title(
      text = top_finding) %>%
    
    hc_subtitle(
      text = subtitle) %>%
    
    hc_caption(
      text = caption_text) %>%
  
   hc_xAxis(title = list(text = ""),
                          labels=list(position="bottom",
                                      style=list(fontSize="12px")),
    categories = list(

      "Southeastern",
      "Mid-City",
      "Central",
      "Eastern",
      "Northeastern",
      "Western",
      "Northwestern",
      "Northern",
      "Southern"
      
      
    ))%>%
   hc_yAxis(title = list(text = paste0(""),
                          labels = list(style=list(fontSize="12px"))))%>%
      hc_add_theme(cc_theme)%>%
    hc_chart(
      marginRight=120) %>%
  
  hc_legend(enabled = TRUE, 
              # reversed =  TRUE,
              x=20)%>% 
    
    hc_exporting(
      enabled = TRUE, sourceWidth=900, sourceHeight=600, 
      chartOptions=list(plotOptions=list(series=list(dataLabels=list(enabled=TRUE,format='{point.rate:.1f}%')))),
      filename = paste0(subtitle,"_Catalyst California, catalystcalifornia.org, 2023."),
      buttons=list(contextButton=list(menuItems=list('downloadPNG', 'downloadSVG',
                                                     'downloadXLS', 'downloadCSV'))))




dbDisconnect(pillars_conn)
```

```{r, echo=FALSE}
chart
```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>