---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

#### Testing bubblepop ####
library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")

## Load in RJS Pillars data
df <- dbGetQuery(pillars_conn, "SELECT * FROM report_stoprates_result_race_person") 
meta<-dbGetQuery(pillars_conn, "SELECT * FROM metadata_race_labels")


# Stacked bar graph for Warning/No Action:

df<-df%>%
 filter(result_simple=="Warning (verbal or written)" | result_simple =="No Action")%>%
left_join(meta, by=c("race"="race_base"))%>%
  filter(race!="aian" & race != "nhpi" & race != "sswana")%>% # filter out aian/nhpi/sswana for now
  group_by(race)%>%
  mutate(count_comb=sum(count),
         rate_comb=count_comb/total*100)%>%#aggregate No Action/Warning
  arrange(-rate)

tooltip_text <- "For every 100 <b>{point.race_label_short:.1f}</b> people stopped by SDPD, officers stopped <b>{point.rate:.1f}</b> people they perceived as <b>{point.race_label_short:.1f}</b> for stops that only resulted in <b>{point.result_simple:.1f}</b>, a total of <b>{point.count:,0f}</b> people."

tooltip_text <- sapply(strwrap(tooltip_text, 110, simplify=FALSE), paste, collapse="<br>")

 # custom order the groups on the stacked bar graph
df <- within(df, result_simple <- factor(result_simple, levels=c("Warning (verbal or written)", "No Action")))

# add methodnote
methodnote <- "Analysis for all officer-initiated stops."

# create caption
caption_text <- paste("<br><br>", sourcenote, racenote, methodnote)

## graph

group_colors = c(lavender, meteorite)

chart<-hchart(df, 
         "bar", hcaes(x = race_label_short, y = rate, group = result_simple),
         stacking = "normal",
         tooltip =  list(headerFormat='',pointFormat=tooltip_text)) %>%
    
    hc_title(
      text = 'SDPD is most likely to stop Black and Latinx people for stops that result in no action') %>%
    
    hc_subtitle(
      text = 'Percent of officer-initiated stops that result in a warning or no action by race') %>%
    
    hc_caption(
      text = caption_text) %>%
    
    hc_yAxis(title = list(text = paste0(""))) %>%
    
    hc_xAxis(categories = list("Black","Latinx", "AIAN", 'White', "Asian", "NHPI", "SWANA/SA",  "Multiracial"),
             title = list(text = paste0(""),
                          labels=list(position="bottom"))) %>%
    
    hc_legend(enabled = TRUE, 
              reversed =  TRUE,
              x=20)%>% 
    
    hc_add_theme(cc_theme)%>%
    
    hc_colors(group_colors) %>%
    hc_chart(
      marginRight=120) %>%
    
    hc_exporting(
      enabled = TRUE, sourceWidth=900, sourceHeight=600, 
      chartOptions=list(plotOptions=list(series=list(dataLabels=list(enabled=TRUE,format='{point.rate:.1f}%')))),
      filename = paste0("Percent of officer-initiated stops that result in a warning or no action by race","_Catalyst California, catalystcalifornia.org, 2023."),
      buttons=list(contextButton=list(menuItems=list('downloadPNG', 'downloadSVG',
                                                     'downloadXLS', 'downloadCSV'))))



dbDisconnect(pillars_conn)


```

```{r, echo=FALSE}
chart

```



<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>