---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")

meta<-dbGetQuery(pillars_conn, "SELECT * FROM metadata_race_labels")%>%
  mutate(race_label_short=ifelse(race_base %in% "nh_twoormor", "Two or more", race_label_short))

df <- dbGetQuery(pillars_conn, "SELECT * FROM report_timespent_ficard_race_stop") %>%
  left_join(meta, by=c("race"="race_base"))%>%
  mutate(race_label_short=ifelse(race %in% "nh_multi_race", "Multiracial", race_label_short))%>%
filter(race!="nh_sswana" & race !="aian" & race !="nhpi")

# Combine nh_twoormor and nh_multi_racial into one multiracial category with a combined duration_total and duration_rate.
# Remove the original, separate nh_twoormor and nh_multi_racial after combining

df<-df %>%
  filter(race %in% c("nh_twoormor", "nh_multi_race")) %>%
  summarize(race = "nh_combined", across(c(duration_count), sum)) %>%
  mutate(level="Field interview card completed",
         duration_total=118970.3,
         duration_rate=duration_count/duration_total*100,
         race_label_short="Multiracial"
         )%>%
  bind_rows(df, .)%>%
  filter(!grepl("nh_twoormor|nh_multi_race", race))


# custom item coloring
group_colors_item <- c("#211447","#D6D6D6", meteorite, "#E2D9FF",peridot, "#E7FF39", "#F0FF85", "#BDAFE9")

# add methodnote
methodnote <- "Analysis for all officer-initiated stops resulting in a field interview card only. Officers spent a total of 118,970.3 hours on officer-initiated stops that resulted in a field interview card only in 2022."

# create caption
caption_text <- paste("<br><br>", racenote, sourcenote, methodnote)

# graph
chart <- fx_itemchart(
    df=df, 
    x="race_label_short",
    y="duration_rate", 
    group_colors=group_colors_item,
    # row_nums=5, # integer
    top_finding="SDPD spends most of their time on field interview cards for Latinx and Black people relative to their population and other groups",
    subtitle= "Percent of hours officers spend conducting stops resulting in a field interview card by race",
    tooltip_text="Out of 100 hours spent on <b>officer-initiated stops resulting in a field interview card</b>, SDPD spent <b>{point.duration_rate:.1f}</b> hours conducting field interviews for people perceived as <b>{point.race_label_short}</b>",
    legend_text="Single dot represents 1 hour out of 100 hours",
    caption = caption_text)    

dbDisconnect(pillars_conn)
```

```{r, echo=FALSE}
chart
```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>