---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

#### Testing bubblepop ####
library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")
## load in race metadata
metadata_race_labels <-  dbGetQuery(pillars_conn, "SELECT * FROM metadata_race_labels") %>% select(race_base, race_label_short, race_label_long)

## Load in RJS Pillars data: Bubble Pop test ##
report_hitrates_race_person <- dbGetQuery(pillars_conn, "SELECT * FROM data.report_hitrates_race_person") %>% filter(race == "total")

# filter for total
df_no_contraband <- report_hitrates_race_person %>% mutate(label = "No Contraband or Evidence Found") %>% rename(count = no_contraband_count, rate = no_contraband_rate)

# calculate contraband
df_contraband <- report_hitrates_race_person %>% filter(race == "total") %>% mutate(label = "Contraband or Evidence Found", count = searches_count - no_contraband_count, rate = 100-no_contraband_rate) %>% select(-no_contraband_count, -no_contraband_rate)

df <- rbind(df_no_contraband, df_contraband)
  
  
chart <- 
df %>%
  hchart(
    "pie", hcaes(x = label, y = rate),
    name = "",
    tooltip = list(headerFormat="", pointFormat = "<b>{point.rate:.1f}%</b> of people SDPD searched had <b>{point.label}</b>,<br>for a total of <b>{point.count:,.0f}</b> people needlessly searched."),
     innerSize="65%",
     center = c(50, 50), 
    )%>% 
  hc_title(text = "Most searches SDPD conducts yield no evidence or contraband",
 align="left")%>%
   hc_subtitle(text = "Percent of people searched by whether contraband or evidence is found",
                     align="left") %>%
  hc_caption(
    text = paste0("<br><br>", sourcenote, " Analysis for all officer-initiated stops."))%>%
  hc_add_theme(cc_theme_donut)%>%
  hc_plotOptions(
    innersize="50%", 
    startAngle=90, 
    endAngle=90,
    center=list('50%', '75%'),
    size='120%',
    colors=c(peridot, meteorite))%>%
  hc_exporting(
    enabled = TRUE, sourceWidth=900, sourceHeight=600, 
    chartOptions=list(plotOptions=list(series=list(dataLabels=list(enabled=TRUE, format='{point.hours_rate_cap:.1f}%')))),
    filename = paste0("Percentage of searches by whether contraband or evidence was found","_Catalyst California, catalystcalifornia.org, 2023.")
  )



dbDisconnect(pillars_conn)
```

```{r, echo=FALSE}
chart
```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>