---
title: ""
output:
  html_document
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

#### Testing bubblepop ####
library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("W:\\Project\\RJS\\Pillars\\GitHub\\HK\\sdpillars\\report_embeds\\chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")

## Load in RJS Pillars data
df <- dbGetQuery(pillars_conn, "SELECT * FROM report_stoprates_result_race_person") 
meta<-dbGetQuery(pillars_conn, "SELECT * FROM metadata_race_labels")

# Aggregate to combine No Action/Warning into one result: I don't find that these results are as compelling we don't see as many racial disparities across rates, I think I would vote to do the stacked bar graph route

df_combine<-df%>%
    filter(result_simple=="Warning (verbal or written)" | result_simple =="No Action")%>%
  group_by(race)%>%
  mutate(count_warningnoaction=sum(count),
         rate_warningnoaction=count_warningnoaction/total*100)%>%
  slice(1)

# Stacked bar graph for Warning/No Action:

df<-df%>%
 filter(result_simple=="Warning (verbal or written)" | result_simple =="No Action")%>%
left_join(meta, by=c("race"="race_base"))


tooltip_text <- "For every 100 people <b>{point.race_label_short:.1f}</b> people in San Diego stopped for an officer-initiated stop, SDPD stopped <b>{point.rate:.1f}</b> people perceived as <b>{point.race_label_short:.1f}</b> for stops that resulted in  <b>{point.result_simple:.1f}</b>, a total of <b>{point.count:,0f}</b> people."

chart <- fx_stackedbarchart(  
  df = df,
  x = 'race_label_short',
  y = 'rate',
  group_var = 'result_simple',
  group_colors = group_colors_item,
  top_finding = 'A top level finding about systemic impact',
  subtitle = 'stop rates for field interviews for every race across age brackets',
  tooltip = tooltip_text,
  caption = paste0(racenote,"<br><br>", sourcenote, "<br>","Analysis for all officer-initiated stops.","<br>"))

```

```{r, echo=FALSE}
chart

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, result='hide', include=FALSE}


dbDisconnect(pillars_conn)


```



<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>