---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")

df <- dbGetQuery(pillars_conn, "SELECT * FROM report_stoprates_arrest_gang_race_person") 

meta<-dbGetQuery(pillars_conn, "SELECT * FROM metadata_race_labels")%>%
  mutate(race_label_short=ifelse(race_base %in% "nh_twoormor", "Two or more", race_label_short))

# for visualizing, lets keep the top 3 rates within each racial group and grab race labels:

df<-df %>% 
  arrange(-rate) %>% 
group_by(race)%>%
slice(1:3)%>%
  left_join(meta, by=c("race"="race_base"))

# clean up final table and columns we want to visualize

df<-df%>%
  ungroup()%>%
  select(race_label_short, resulttext, total, count,rate)%>%
  rename("Reason for Arrest without Warrant" = "resulttext",
         "Race"="race_label_short",
         "Total"="total",
         "Count"="count",
         "Rate (%)"="rate")

# add method note 
methodnote <- "Analysis for all officer-initiated stops that resulted in a custodial arrest without a warrant made by officers assigned to gang enforcement."

# create caption 
caption_text <- paste(sourcenote, methodnote)

# create table
library(flextable)

ft <- flextable(df)%>%
  colformat_double(j = c("Total", "Count",
                             "Rate (%)"), digits = 1)%>%
 set_table_properties(layout = "autofit", width = .75)%>%
  set_caption("Top 3 Reasons for Arrest without Warrant by Race")%>%
   add_footer_lines(caption_text)

dbDisconnect(pillars_conn)

```

```{r, echo=FALSE}

ft

```



<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>