---
title: ""
output:
  html_document
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")

meta<-dbGetQuery(pillars_conn, "SELECT * FROM metadata_race_labels")%>%
  mutate(race_label_short=ifelse(race_base %in% 'aian',"AIAN Alone or in Combination",
                                 ifelse(race_base %in% 'nhpi', "NHPI Alone or in Combination",
                                        ifelse(race_base %in% 'aian', 'AIAN Alone or in Combination', race_label_short))))%>%
  filter(race_base!="nh_sswana" & race_base != "total")

pop<-dbGetQuery(pillars_conn, "SELECT * FROM report_stoprates_ficard_race_pop_person") %>%
  left_join(meta, by=c("race"="race_base"))%>%
  arrange(-rate)

offit<-dbGetQuery(pillars_conn, "SELECT * FROM report_stoprates_ficard_race_offit_person") %>%
  left_join(meta, by=c("race"="race_base"))

# pop denominator--------

# TITLE 
title_text <- paste0("SDPD disproportionately conducts field interviews for Black people living in San Diego")

# SUBTITLE
subtitle_text <- paste0("Rate of stops that resulted in a field interview card by race per 1,000 people of that racial group in San Diego")

# CAPTION
caption_text <- paste0(racenote,"<br><br>", sourcenote, "<br>","Analysis for all officer-initiated stops resulting in a field interview card only.","<br>")

# TOOLTIP
tooltip_text <- "Out of 1,000 <b>{point.race_label_short:.0f}</b> people in San Diego, <b>{point.rate:.1f}</b>  people perceived as <b>{point.race_label_short:.0f}</b> are stopped for an officer-initiated stop that results in a field interview card"

chart <- fx_bubblepopchart(
  df=pop,
  x='race_label_short', # format for your data frame
  y='rate', # format for your data frame
  z='count', # format for your data frame
  top_finding=title_text,
  subtitle= subtitle_text,
  tooltip_text=tooltip_text,
  caption = caption_text,
  yaxis_label = "''", # format for your y axis labels
  export_data_label=list(pointFormat='{point.stop_rate_per1k:.1f} per 1K') # format for your data
) 

chart




dbDisconnect(pillars_conn)

```

```{r, echo=FALSE}
chart
```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>