---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_charts.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

library(RPostgreSQL)
library(tidyverse)
source("W:\\RDA Team\\R\\credentials_source.R")
source("chart_functions.R")

# add budget data
programs<-c("Police","Fire-Rescue","Other","Citywide Program Expenditures","Parks & Recreation","Transportation","City Attorney","Library","Environmental Services","Stormwater","Facilities Services","Economic Development")
budget<-c(593.3,308.7,168.6,150.3,133.9,82.5,68.8,60.7,58.8,51.6,23.6,22.5)

df<-data.frame(programs,budget)

# remove extra rows
df_final<-df%>%filter(programs!='Other' & programs!='Citywide Program Expenditures')


```


```{r, include=FALSE}

# add methodnote
methodnote <- "Other and Citywide Program expenditures respectively comprised $168.6 and $150.3 million of the city's general fund in 2022. City of San Diego, Review of FY 2022 Proposed Budget. Available at https://www.sandiego.gov/sites/default/files/12-10_iba_review_of_fiscal_year_2022_proposed_budget.pdf."

# create caption
caption_text <- paste("<br>", methodnote)

# add title and subtitle
top_finding<-"The city's expenditures on SDPD were the largest for any department"
subtitle<-"The City of San Diego's fiscal year 2022 adopted general fund expenditures by department (in millions)"

# tooltip

tooltip_text<- paste0("The city's general fund expenditures on <b>{point.programs}</b> totaled <b>${point.budget} million</b> in fiscal year 2022.")

# Final Graph----------------

# set ordering

chart<-df_final%>% arrange(desc(budget))%>%
  hchart('column', hcaes(x = programs, y = budget),
         tooltip =  list(headerFormat='',pointFormat=tooltip_text))%>%
         hc_chart(events = list(load = JS("function() {
        const chart = this;
        chart.series[0].data.forEach(function(point) {
          if (point.y <= 500) {
            point.update({
              color: meteorite
            })
          }

          if (point.y > 500) {
            point.update({
              color: lavender
            })
          }
        });
      }
    ")
  ),marginRight=120) %>%
  hc_colors(c(meteorite))%>%
   hc_title(
      text = top_finding) %>%
    
    hc_subtitle(
      text = subtitle) %>%
    
    hc_caption(
      text = caption_text) %>%
  
   hc_xAxis(title = list(text = ""),
                          labels=list(position="bottom",
                                      style=list(fontSize="12px")))%>%
   hc_yAxis(title = list(text = paste0(""),
                          labels = list(style=list(fontSize="12px"))),max=700)%>%
      hc_add_theme(cc_theme)%>%
    # hc_chart(
    #   marginRight=120) %>%
  
  hc_legend(enabled = TRUE, 
              # reversed =  TRUE,
              x=20)%>% 
    
    hc_exporting(
      enabled = TRUE, sourceWidth=900, sourceHeight=600, 
      chartOptions=list(plotOptions=list(series=list(dataLabels=list(enabled=TRUE,format='${point.budget:.1f}')))),
      filename = paste0(subtitle,"_Catalyst California, catalystcalifornia.org, 2023."),
      buttons=list(contextButton=list(menuItems=list('downloadPNG', 'downloadSVG',
                                                     'downloadXLS', 'downloadCSV'))))


```

```{r, echo=FALSE}
chart
```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>