---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_charts.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")

df <- dbGetQuery(pillars_conn, "SELECT * FROM report_stoprates_reason_ficard_race_person")
meta<-dbGetQuery(pillars_conn, "SELECT * FROM metadata_race_labels")

df<-df%>%
  left_join(meta, by=c("race"="race_base"))%>%
  filter(race!='nh_sswana' & race !="nhpi" & race != 'aian' & race!='total') %>%
  mutate(reason_simple=ifelse(reason_simple=='Known to be on Parole / Probation / PRCS / Mandatory Supervision',
                              'Probation/Parole',ifelse(reason_simple=='Investigation to determine whether the person was truant','Truancy Investigation',ifelse(reason_simple=="Consensual Encounter resulting in a search", "Consensual Encounter/Search",ifelse(reason_simple=="Knowledge of outstanding arrest warrant/wanted person","Warrant",reason_simple)))))

df <- within(df, reason_simple <- factor(reason_simple, levels=c("Truancy Investigation","Warrant","Consensual Encounter/Search","Probation/Parole","Reasonable Suspicion","Traffic Violation")))

df<-df%>%filter(reason_simple=="Traffic Violation")%>%arrange(-rate)

tooltip_text <- "Across all people perceived as <b>{point.race_label_short:.1f}</b> who had a field interview card<br>completed, officers used <b>{point.reason_simple:.1f}s</b> as the primary reason<br>for the stop <b>{point.rate:.1f}%</b> of the time."

title_text<-paste0("SDPD is more likely to use traffic violations to profile people of color for field interviews compared to White people")
    
subtitle_text<-paste0("Percent of people who are field interviewed and originally stopped for traffic violations by race")

# add methodnote
methodnote <- "Analysis for all officer-initiated stops that only resulted in a field interview card completed."

## create caption
caption_text <- paste("<br>", racenote, sourcenote, methodnote)


chart <- fx_bubblepopchart(
  df=df,
  x='race_label_short', # format for your data frame
  y='rate', # format for your data frame
  z='count', # format for your data frame
  top_finding=title_text,
  subtitle= subtitle_text,
  tooltip_text=tooltip_text,
  caption = caption_text,
  yaxis_label = "''" # format for your y axis labels
)

dbDisconnect(pillars_conn)
```

```{r, echo=FALSE}
chart
```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>