---
title: ""
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

#### Testing bubblepop ####
library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")

## Load in RJS Pillars data: Bubble Pop test ##
df <- dbGetQuery(pillars_conn, "SELECT * FROM report_stopsrates_result_race_person")  %>% filter(race!="total" )

## add methodnote
methodnote <- "Analysis for all officer-initiated stops."

## create caption
caption_text <- paste("<br><br>", racenote, sourcenote, methodnote)

# For now, lets just filter and visualize result == Warning

df<-df%>%
  filter(result_simple=="Citation for infraction")%>%
mutate(race=ifelse(race %in% "nh_aian", "NH AIAN",
        ifelse(race %in% "nh_nhpi", "NH NHPI",
          ifelse(race %in% "sswana", "SSWANA",
                 ifelse(race %in% "nh_white", "White",
                        ifelse(race %in% "nh_black", "Black",
                               ifelse(race %in% "nh_asian", "Asian",
                                      ifelse(race %in% "latinx", "Latinx",
                                             ifelse(race %in% "aian", "AIAN",
                                                    ifelse(race %in% "nh_sswana", "NH SSWANA",
                                                           ifelse(race %in% "nh_twoormor", "Multiple Races",
                                                                  "NHPI")))))))))))%>%
  arrange(-rate)
                  

chart <- fx_bubblepopchart(
  df=df, 
  x='race', 
  y='rate', 
  z='count',
  top_finding=paste0("SDPD disproportionately makes stops that result in no action against Black and Latinx people"),
  
  subtitle= paste0("Number of officer-initiated stops resulting in no action by race"), 
  
  tooltip_text="For every 100 <b>{point.race:.1f}</b> people in San Diego stopped for an officer-initiated stop, SDPD stopped <b>{point.rate:.1f}</b> people perceived as <b>{point.race:.1f}</b> for stops that resulted in No Action, for a total of <b>{point.count:,0f}</b> people.", # customize your tooltip as a statement, calling out rate and count
  
  caption = caption_text, # if necessary add a method note between the racenote and sourcenote with a line break, use racenote if graph includes data by race, and always use sourcenote. Each of these are standard objects across all charts
  yaxis_label = "''", #format for your y axis labels
  export_data_label=list(pointFormat='{point.rate:.1f}')
)

```

```{r, echo=FALSE}
chart

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, result='hide', include=FALSE}


dbDisconnect(pillars_conn)


```



<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>