



```{r, include=FALSE}
#### Map ###
#### Load libraries ####
library(usethis)
library(tidyverse)
library(sf)
library(leaflet)
library(sp)
library(htmltools) # for html escape
library(magrittr)
library(RPostgreSQL)
library(htmlwidgets)

source("W:\\RDA Team\\R\\credentials_source.R")
source("W:\\Project\\RJS\\Pillars\\GitHub\\HK\\sdpillars\\report_embeds\\chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")
## load in race metadata
metadata_race_labels <-  dbGetQuery(pillars_conn, "SELECT * FROM metadata_race_labels") %>% select(race_base, race_label_short, race_label_long)

## Load in RJS Pillars data ##
df_long <- dbGetQuery(pillars_conn, "SELECT * FROM data.report_hitrates_div_race_ficard_person")
div <- st_read(pillars_conn, query =  "SELECT * FROM data.sangis_sdpd_divisions_2023") 
# transform for leaflet

div<- st_transform(div,4326)

# go from long to wide

df_wide <- df_long %>% pivot_wider(
  names_from = race,
  values_from = stop_count:no_contraband_prc_rate,
  names_sep = "_"
  
)

# merge division sf by df: this is only for the shapefile
div_wide_sf <- div %>% left_join(df_wide)

# the dot density needs the data to be long
div_long_sf <- div %>% left_join(df_long)
```


```{r, include=FALSE}
### Calculate dot density count ###
sdpd_ripa_dots = as_dot_density(
  div_long_sf,
  value = "no_contraband_count",
  values_per_dot = 5, ## each dot represents 
  group = "race"
)

# Filter for race groups
#df %>% as.data.frame() %>% group_by(race) %>% summarize(count = n())
nh_black_dots <- sdpd_ripa_dots %>% filter(race == "nh_black")
nh_white_dots <- sdpd_ripa_dots %>% filter(race == "nh_white")
aian_dots <- sdpd_ripa_dots %>%  filter(race == "aian")
nh_aian_dots <- sdpd_ripa_dots %>%  filter(race == "nh_aian")
latinx_dots <- sdpd_ripa_dots %>% filter(race == "latinx")
#nh_sswana_dots <- sdpd_ripa_dots %>% filter(race == "nh_sswana")
sswana_dots <- sdpd_ripa_dots %>% filter(race == "sswana")
nh_asian_dots <- sdpd_ripa_dots %>% filter(race == "nh_asian")
nh_twoormor_dots <- sdpd_ripa_dots %>% filter(race == "nh_twoormor")
nhpi_dots <- sdpd_ripa_dots %>% filter(race == "nhpi")
nh_nhpi_dots <- sdpd_ripa_dots %>% filter(race == "nh_nhpi")


## function to change the legend shape and color
colors_function <- function(colors, sizes, borders, shapes) {
  shapes <- gsub("circle", "100%", shapes)
  shapes <- gsub("square", "100%", shapes)
  paste0(colors, "; width:", sizes, "px; height:", sizes, "px; border:1px solid ", borders, "; border-radius:", shapes)
}



```


```{r, include=FALSE}
rate_popup <- paste0(
  
  
  label = paste0(
     "<div class='leaflet-popup-scrolled' style='max-width:800px;max-height:200px'>", 
     
   "In Division <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$div_num, 
   
   "</span>, <br> <br> Out of <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$stop_count_nh_black,  "</span> searches conducted during traffic stops for individuals perceives as <span style='font-size: 14px; font-weight: bold;'>", "Black",  "</span> where a field interview card was completed, SDPD found no contraband/evidence in <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$no_contraband_count_nh_black, "</span> stops, a no hit rate of <span style='font-size: 14px; font-weight: bold;'>", round(div_wide_sf$no_contraband_prc_rate_nh_black, digits = 1), "</span>%.</br>",
   
   "</span> <br> Out of <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$stop_count_nh_white,  "</span> searches conducted during traffic stops for individuals perceives as <span style='font-size: 14px; font-weight: bold;'>", "White", "</span> where a field interview card was completed, SDPD found no contraband/evidence in <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$no_contraband_count_nh_white, "</span> stops, a no hit rate of <span style='font-size: 14px; font-weight: bold;'>", round(div_wide_sf$no_contraband_prc_rate_nh_white, digits = 1), "</span>%. </br>",
   
     "</span> <br> Out of <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$stop_count_nh_aian,  "</span> searches conducted during traffic stops for individuals perceives as <span style='font-size: 14px; font-weight: bold;'>", "Non-Hispanic American Indian and Alaska Native", "</span> where a field interview card was completed, SDPD found no contraband/evidence in <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$no_contraband_count_nh_aian, "</span> stops, a no hit rate of <span style='font-size: 14px; font-weight: bold;'>", round(div_wide_sf$no_contraband_prc_rate_nh_aian, digits = 1), "</span>%. </br>",
   
        "</span> <br> Out of <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$stop_count_aian,  "</span> searches conducted during traffic stops for individuals perceives as <span style='font-size: 14px; font-weight: bold;'>", "American Indian and Alaska Native", "</span> where a field interview card was completed, SDPD found no contraband/evidence in <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$no_contraband_count_aian, "</span> stops, a no hit rate of <span style='font-size: 14px; font-weight: bold;'>", round(div_wide_sf$no_contraband_prc_rate_aian, digits = 1), "</span>%. </br>",
   
     "</span> <br> Out of <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$stop_count_nh_nhpi,  "</span> searches conducted during traffic stops for individuals perceives as <span style='font-size: 14px; font-weight: bold;'>", "Non-Hispanic Native Hawaiian or Pacific Islander", "</span> where a field interview card was completed, SDPD found no contraband/evidence in <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$no_contraband_count_nh_nhpi, "</span> stops, a no hit rate of <span style='font-size: 14px; font-weight: bold;'>", round(div_wide_sf$no_contraband_prc_rate_nh_nhpi, digits = 1), "</span>%. </br>",
   
        "</span> <br> Out of <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$stop_count_nhpi,  "</span> searches conducted during traffic stops for individuals perceives as <span style='font-size: 14px; font-weight: bold;'>", "Native Hawaiian or Pacific Islander", "</span> where a field interview card was completed, SDPD found no contraband/evidence in <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$no_contraband_count_nhpi, "</span> stops, a no hit rate of <span style='font-size: 14px; font-weight: bold;'>", round(div_wide_sf$no_contraband_prc_rate_nhpi, digits = 1), "</span>%. </br>",
   
     "</span> <br> Out of <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$stop_count_latinx,  "</span> searches conducted during traffic stops for individuals perceives as <span style='font-size: 14px; font-weight: bold;'>", "Latinx", "</span> where a field interview card was completed, SDPD found no contraband/evidence in <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$no_contraband_count_latinx, "</span> stops, a no hit rate of <span style='font-size: 14px; font-weight: bold;'>", round(div_wide_sf$no_contraband_prc_rate_latinx, digits = 1), "</span>%. </br>",
   
      "</span> <br> Out of <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$stop_count_sswana,  "</span> searches conducted during traffic stops for individuals perceives as <span style='font-size: 14px; font-weight: bold;'>", "Southwest Asian or North African/Middle Eastern or North African or South Asian", "</span> where a field interview card was completed, SDPD found no contraband/evidence in <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$no_contraband_count_sswana, "</span> stops, a no hit rate of <span style='font-size: 14px; font-weight: bold;'>", round(div_wide_sf$no_contraband_prc_rate_sswana, digits = 1), "</span>%. </br>", 
   
    "</span> <br> Out of <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$stop_count_nh_asian,  "</span> searches conducted during traffic stops for individuals perceives as <span style='font-size: 14px; font-weight: bold;'>", "Asian", "</span> where a field interview card was completed, SDPD found no contraband/evidence in <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$no_contraband_count_nh_asian, "</span> stops, a no hit rate of <span style='font-size: 14px; font-weight: bold;'>", round(div_wide_sf$no_contraband_prc_rate_nh_asian, digits = 1), "</span>%. </br>",
   
       "</span> <br> Out of <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$stop_count_nh_twoormor,  "</span> searches conducted during traffic stops for individuals perceives as <span style='font-size: 14px; font-weight: bold;'>", "Two or More Races", "</span> where a field interview card was completed, SDPD found no contraband/evidence in <span style='font-size: 14px; font-weight: bold;'>", div_wide_sf$no_contraband_count_nh_twoormor, "</span> stops, a no hit rate of <span style='font-size: 14px; font-weight: bold;'>", round(div_wide_sf$no_contraband_prc_rate_nh_twoormor, digits = 1), "</span>%. </br>"))
  

```

```{r, include=FALSE}
# colors according to our brand guide: https://catalystcalifornia.sharepoint.com/sites/Portal/AP%20Projects/Forms/AllItems.aspx?FolderCTID=0x012000EF0283621C7FE048A8E68512F119353B&id=%2Fsites%2FPortal%2FAP%20Projects%2FCommunications%2FCatalyst%20California%2FBranding%20Materials%20%2B%20Templates%2FVisual%20Brand%20Guide%2FCatalyst%20California%20Brand%20Guide%5FSeptember%202022%2Epdf&viewid=1aaeb4a9%2D2232%2D41c7%2Da71c%2D727af9e1f5d7&parent=%2Fsites%2FPortal%2FAP%20Projects%2FCommunications%2FCatalyst%20California%2FBranding%20Materials%20%2B%20Templates%2FVisual%20Brand%20Guide

# Base Color 00
lime_green <- c('#0AB013')
persian_indigo <- c('#211447')
halloween_orange <- c('#DF4007')
bitter_lemon <- c('#BCD313')
blue <- c('#0860BC')
dark_tangerine <- c('#EB8D00')
american_yellow <- c('#EABB00')
halaya_ube <- c('#601D42')

#dark_silver <- c('#6F6F6F') ## remove these


### change size of legend

map <-  leaflet(width = "100%", height = "600px") %>%
   
    
  ## add NH Black Stops
  
addCircleMarkers(data = nh_black_dots, group = "Black", label = NULL, weight = 2, fillOpacity = 1, radius = 2, color="white",  fillColor=blue, stroke = TRUE) %>% 
  
  ## add NH White Stops
  
 addCircleMarkers(data = nh_white_dots, group = "White", label = NULL, weight = 2, fillOpacity = 1, radius = 2, color="white",  fillColor=  bitter_lemon,  stroke = TRUE) %>% 
  
  
  ### add NH AIAN dots 
  
 addCircleMarkers(data = nh_aian_dots,  group = "Non-Hispanic AIAN", label = NULL, weight = 2, fillOpacity = 1, radius = 2, color="white",  fillColor= dark_tangerine, stroke = TRUE) %>% 
   
  ### add AIAN dots 
  
 addCircleMarkers(data = aian_dots,  group = "AIAN", label = NULL, weight = 2, fillOpacity = 1, radius = 2, color="white",  fillColor= dark_tangerine, stroke = TRUE) %>% 
  
  ### add latinx dots
  
 addCircleMarkers(data = latinx_dots, group = "Latinx", label = NULL, weight = 2, fillOpacity = 1, radius = 2, color="white",  fillColor= lime_green,  stroke = TRUE) %>% 
  
  ### add sswana dots
  
 addCircleMarkers(data = sswana_dots, group = "SSWANA", label = NULL, weight = 2, fillOpacity = 1, radius = 2, color="white",  fillColor= american_yellow, stroke = TRUE) %>% 
  
  ### add nh asian dots
  
 addCircleMarkers(data = nh_asian_dots, group = "Asian", label = NULL, weight = 2, fillOpacity = 1, radius = 2, color="white",  fillColor=  halloween_orange, stroke = TRUE) %>% 
  
  ### add nh two or more dots
  
 addCircleMarkers(data = nh_twoormor_dots, group = "Two or More Races", label = NULL, weight = 2, fillOpacity = 1, radius = 2, color="white",  fillColor= persian_indigo, stroke = TRUE) %>% 
  
  ### add nh_nhpi dots
  
 addCircleMarkers(data = nh_nhpi_dots, group = "Non-Hispanic NHPI", label = NULL, weight = 2, fillOpacity = 1, radius = 2, color="white",  fillColor= halaya_ube, stroke = TRUE) %>% 
   
     ### add nhpi dots
  
 addCircleMarkers(data = nhpi_dots, group = "NHPI", label = NULL, weight = 2, fillOpacity = 1, radius = 2, color="white",  fillColor= halaya_ube, stroke = TRUE) %>% 
  
   # add Division 
  addPolygons(data = div_wide_sf, label=~htmlEscape(paste0("Division ", div_num)),
              color = "black", fillColor = "white", opacity = 1,  popup = ~paste0(rate_popup), 
            weight = 2, smoothFactor = 0.5,  highlight = highlightOptions(color = "white", weight = 3, bringToFront = TRUE, sendToBack = FALSE)) %>%
   
  addLayersControl(overlayGroups = c("Black", "Latinx", "Asian", "White",  "SSWANA", "NHPI", "Non-Hispanic NHPI", "AIAN", "Non-Hispanic AIAN", "Two or More Races"),
                   options = layersControlOptions(collapsed = FALSE)) %>%

  addProviderTiles("CartoDB.Positron") %>%
  setView(-117.13395, 32.79923, zoom = 10) %>% #base and view 
  
  hideGroup(c("White", "AIAN", "NHPI"))   # hide white group

```


```{r, echo=FALSE}
map
```

<div align="left" style="line-height: 1em;"><span style="font-size: 10px;">Race/ethnicity: AIAN=American Indian or Alaska Native, NHPI=Native Hawaiian or Pacific Islander, MESA=Middle Eastern or South Asian; Observations by race may overlap in the point density map. </span> <br> 
<span style=' font-size: 10px;'>Catalyst California's calculations based on City of San Diego's Police Stop Data (2022); <u>[Catalyst California](https://www.catalystcalifornia.org)</u>, 2023. Analysis for all officer-initiated stops.</span> </div>


