---
title: ""
output:
  html_document
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

#### Testing bubblepop ####
library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("W:\\Project\\RJS\\Pillars\\GitHub\\HK\\sdpillars\\report_embeds\\chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")

stoprates_age_race_ficard_person <- dbGetQuery(pillars_conn, "SELECT * FROM data.report_stoprates_age_race_ficard_person")

race_levels<-c("latinx","nh_asian","nh_black","nh_nhpi","nh_white", "aian", "nhpi", "sswana", "nh_twoormor")
race_labels<-c("latinx","nh_asian","nh_black","nh_nhpi","nh_white", "aian", "nhpi", "sswana", "nh_twoormor")
stoprates_age_race_ficard_person$race<-factor(stoprates_age_race_ficard_person$race, ordered=TRUE, 
                                               levels=race_levels, labels=race_labels)

tooltip_text <- "Across all field interviews of folks <b> ages {point.age_bracket:.1f} </b>, SDPD stopped <b>{point.race:.1f} people {point.rate:.1f}% of the time.</b>"

chart <- fx_stackedbarchart(  
  df = stoprates_age_race_ficard_person,
  x = 'age_bracket',
  y = 'rate',
  group_var = 'race',
  group_colors = group_colors_item,
  top_finding = 'A top level finding about systemic impact',
  subtitle = 'stop rates for field interviews for every race across age brackets',
  tooltip = tooltip_text,
  caption = paste0(racenote,"<br><br>", sourcenote, "<br>","Analysis for all officer-initiated stops.","<br>"))

dbDisconnect(pillars_conn)
```

```{r, echo=FALSE}
chart
```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>