---
title: ""
output:
  html_document
---
<!-- link to Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

```{r, include=FALSE}

#### Testing bubblepop ####
library(RPostgreSQL)
source("W:\\RDA Team\\R\\credentials_source.R")
source("W:\\Project\\RJS\\Pillars\\GitHub\\HK\\sdpillars\\report_embeds\\chart_functions.R")

pillars_conn <- connect_to_db("rjs_pillars")
timespent_ficard_race_person <- dbGetQuery(pillars_conn, "SELECT * FROM data.report_timespent_ficard_race_person") %>%
  filter(race != "overall")

chart <- fx_itemchart(
    df=timespent_ficard_race_person, 
    x="race",
    y="duration_rate", 
    group_colors=group_colors_item,
    # row_nums=5, # integer
    top_finding="The top finding related to systemic factors",
    subtitle= "The number of hours SDPD spent conducting field interviews by race",
    tooltip_text="Out of 100 hours, LBPD spent <b>{point.duration_rate:.1f}</b> hours conducting field interviews on <b>{point.race} people</b>",
    legend_text="Single dot represents 1 hour out of 100 hours",
    caption = paste0(sourcenote," Analysis for all officer-initiated stops RESULTING IN FIELD INTERVIEWS ONLY."))    

dbDisconnect(pillars_conn)
```

```{r, echo=FALSE}
chart
```

<script>
  widg = document.getElementsByClassName('html-widget'); //find widgets
  for (let i = 0; i < widg.length; i++) { //loop through
    document.getElementsByClassName('highchart')[i].style.width = '100%'; //adjust width
    document.getElementsByClassName('highchart')[i].style.height = '100%'; //adjust height
  }
</script>