---
title: "San Diego RIPA Data Pillars Project"
subtitle: "Descriptive Analysis"
author: "Catalyst California"
output:
  html_document:
    css: "W:\\RDA Team\\R\\cc_brandguide.css"
    toc: yes
    toc_depth: 2
    toc_float: yes
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)


list.of.packages <- c("usethis", "highcharter", "tidyverse", "sf", "leaflet", "sp", "htmltools", "magrittr", "flextable", "htmlwidgets")

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

#### Load libraries ####
library(usethis)
library(highcharter)
library(tidyverse)
library(sf)
library(leaflet)
library(sp)
library(htmltools) # for html escape
library(magrittr)
#library(leaflegend) # customize legends to change shapes:: commenting out because not needed for high injury network maps for now
library(flextable)
library(htmlwidgets)


#### Add database connection ####

source("W:\\RDA Team\\R\\credentials_source.R")
con <- connect_to_db("eci_lb_ripa")

```

Before engaging in detailed analysis regarding the project’s research questions, we will first run general frequencies of SDPD stops to get a sense of overall trends. This helps us determine if our expected findings are likely to show up in the data and allows us to identify any trends we did not expect. The analysis will include: 

General counts and percents of SDPD stops by key fields in RIPA data, e.g., stop reason, stop result, calls for service, race, age, searches, officer assignment. 

General counts and percents of stops by Gang Suppression Unit and Special Operations Unit (if available) by key fields in RIPA data, e.g., stop reason, stop result, calls for service, race, age, searches. 

Quick map of stop counts by police beat and for Gang Suppression Unit/Special Operations Unit. 

# SDPD Stop Level Exploration

## SDPD Calls for service versus Officer-initiated

## SDPD stops by stop reason

## SDPD stops by stop result

## SDPD stops by age

## SDPD stops by race

## SDPD stops that were searches and what searches resulted in (hit rates)

# SDPD Gang Suppression Unit Comparisons

## Count and rate of stops across different units

## Gang Suppression Unit Calls for service versus Officer-initiated

## Gang Suppression Unit stops by stop reason

## Gang Suppression Unit stops by stop result

## Gang Suppression Unit stops by age

## Gang Suppression Unit stops by race

# Map

